# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0d11ee299c9843500dd4b91561193ee0884c3930ce53e556f65172bd219a3603c4b797df15a6e77aa307bc57249529f0b913c2b28590af5f1c4adb5e77cc20ff

test:
  secret_key_base: 7425c857fb0033892507b5f0cac5c20142de9fa673eb190daba78c88c387d5cd4283056d313cfe54583b1990029be188e93457347c0acda5e48136c06c4a90e1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
